/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as IllustrationsRouteImport } from './routes/illustrations'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsApiRouteImport } from './routes/docs.api'
import { Route as DocsConceptsRouteImport } from './routes/docs.concepts'
import { Route as DocsDurabilityRouteImport } from './routes/docs.durability'
import { Route as DocsExamplesRouteImport } from './routes/docs.examples'
import { Route as DocsMathRouteImport } from './routes/docs.math'
import { Route as DocsModulesRouteImport } from './routes/docs.modules'
import { Route as DocsProjectorsRouteImport } from './routes/docs.projectors'
import { Route as DocsQuickstartRouteImport } from './routes/docs.quickstart'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IllustrationsRoute = IllustrationsRouteImport.update({
  id: '/illustrations',
  path: '/illustrations',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsApiRoute = DocsApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => DocsRoute,
} as any)
const DocsConceptsRoute = DocsConceptsRouteImport.update({
  id: '/concepts',
  path: '/concepts',
  getParentRoute: () => DocsRoute,
} as any)
const DocsDurabilityRoute = DocsDurabilityRouteImport.update({
  id: '/durability',
  path: '/durability',
  getParentRoute: () => DocsRoute,
} as any)
const DocsExamplesRoute = DocsExamplesRouteImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => DocsRoute,
} as any)
const DocsMathRoute = DocsMathRouteImport.update({
  id: '/math',
  path: '/math',
  getParentRoute: () => DocsRoute,
} as any)
const DocsModulesRoute = DocsModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => DocsRoute,
} as any)
const DocsProjectorsRoute = DocsProjectorsRouteImport.update({
  id: '/projectors',
  path: '/projectors',
  getParentRoute: () => DocsRoute,
} as any)
const DocsQuickstartRoute = DocsQuickstartRouteImport.update({
  id: '/quickstart',
  path: '/quickstart',
  getParentRoute: () => DocsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/illustrations': typeof IllustrationsRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/concepts': typeof DocsConceptsRoute
  '/docs/durability': typeof DocsDurabilityRoute
  '/docs/examples': typeof DocsExamplesRoute
  '/docs/math': typeof DocsMathRoute
  '/docs/modules': typeof DocsModulesRoute
  '/docs/projectors': typeof DocsProjectorsRoute
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/illustrations': typeof IllustrationsRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/concepts': typeof DocsConceptsRoute
  '/docs/durability': typeof DocsDurabilityRoute
  '/docs/examples': typeof DocsExamplesRoute
  '/docs/math': typeof DocsMathRoute
  '/docs/modules': typeof DocsModulesRoute
  '/docs/projectors': typeof DocsProjectorsRoute
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/docs': typeof DocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/illustrations': typeof IllustrationsRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/concepts': typeof DocsConceptsRoute
  '/docs/durability': typeof DocsDurabilityRoute
  '/docs/examples': typeof DocsExamplesRoute
  '/docs/math': typeof DocsMathRoute
  '/docs/modules': typeof DocsModulesRoute
  '/docs/projectors': typeof DocsProjectorsRoute
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/illustrations'
    | '/docs/api'
    | '/docs/concepts'
    | '/docs/durability'
    | '/docs/examples'
    | '/docs/math'
    | '/docs/modules'
    | '/docs/projectors'
    | '/docs/quickstart'
    | '/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/illustrations'
    | '/docs/api'
    | '/docs/concepts'
    | '/docs/durability'
    | '/docs/examples'
    | '/docs/math'
    | '/docs/modules'
    | '/docs/projectors'
    | '/docs/quickstart'
    | '/docs'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/illustrations'
    | '/docs/api'
    | '/docs/concepts'
    | '/docs/durability'
    | '/docs/examples'
    | '/docs/math'
    | '/docs/modules'
    | '/docs/projectors'
    | '/docs/quickstart'
    | '/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRouteWithChildren
  IllustrationsRoute: typeof IllustrationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/illustrations': {
      id: '/illustrations'
      path: '/illustrations'
      fullPath: '/illustrations'
      preLoaderRoute: typeof IllustrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/api': {
      id: '/docs/api'
      path: '/api'
      fullPath: '/docs/api'
      preLoaderRoute: typeof DocsApiRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/concepts': {
      id: '/docs/concepts'
      path: '/concepts'
      fullPath: '/docs/concepts'
      preLoaderRoute: typeof DocsConceptsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/durability': {
      id: '/docs/durability'
      path: '/durability'
      fullPath: '/docs/durability'
      preLoaderRoute: typeof DocsDurabilityRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/examples': {
      id: '/docs/examples'
      path: '/examples'
      fullPath: '/docs/examples'
      preLoaderRoute: typeof DocsExamplesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/math': {
      id: '/docs/math'
      path: '/math'
      fullPath: '/docs/math'
      preLoaderRoute: typeof DocsMathRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/modules': {
      id: '/docs/modules'
      path: '/modules'
      fullPath: '/docs/modules'
      preLoaderRoute: typeof DocsModulesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/projectors': {
      id: '/docs/projectors'
      path: '/projectors'
      fullPath: '/docs/projectors'
      preLoaderRoute: typeof DocsProjectorsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/quickstart': {
      id: '/docs/quickstart'
      path: '/quickstart'
      fullPath: '/docs/quickstart'
      preLoaderRoute: typeof DocsQuickstartRouteImport
      parentRoute: typeof DocsRoute
    }
  }
}

interface DocsRouteChildren {
  DocsApiRoute: typeof DocsApiRoute
  DocsConceptsRoute: typeof DocsConceptsRoute
  DocsDurabilityRoute: typeof DocsDurabilityRoute
  DocsExamplesRoute: typeof DocsExamplesRoute
  DocsMathRoute: typeof DocsMathRoute
  DocsModulesRoute: typeof DocsModulesRoute
  DocsProjectorsRoute: typeof DocsProjectorsRoute
  DocsQuickstartRoute: typeof DocsQuickstartRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsApiRoute: DocsApiRoute,
  DocsConceptsRoute: DocsConceptsRoute,
  DocsDurabilityRoute: DocsDurabilityRoute,
  DocsExamplesRoute: DocsExamplesRoute,
  DocsMathRoute: DocsMathRoute,
  DocsModulesRoute: DocsModulesRoute,
  DocsProjectorsRoute: DocsProjectorsRoute,
  DocsQuickstartRoute: DocsQuickstartRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRouteWithChildren,
  IllustrationsRoute: IllustrationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
