/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as IllustrationsRouteImport } from './routes/illustrations'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsApiRouteImport } from './routes/docs.api'
import { Route as DocsConceptsRouteImport } from './routes/docs.concepts'
import { Route as DocsExamplesRouteImport } from './routes/docs.examples'
import { Route as DocsHostingAndStorageRouteImport } from './routes/docs.hosting-and-storage'
import { Route as DocsMathRouteImport } from './routes/docs.math'
import { Route as DocsModulesRouteImport } from './routes/docs.modules'
import { Route as DocsPriorArtRouteImport } from './routes/docs.prior-art'
import { Route as DocsProjectorsRouteImport } from './routes/docs.projectors'
import { Route as DocsQuickstartRouteImport } from './routes/docs.quickstart'
import { Route as DocsConceptsIndexRouteImport } from './routes/docs.concepts.index'
import { Route as DocsConceptsEventsAndEffectsRouteImport } from './routes/docs.concepts.events-and-effects'
import { Route as DocsConceptsRunsAndThreadsRouteImport } from './routes/docs.concepts.runs-and-threads'
import { Route as DocsConceptsTypeSafetyRouteImport } from './routes/docs.concepts.type-safety'
import { Route as DocsConceptsWaitsAndReplayRouteImport } from './routes/docs.concepts.waits-and-replay'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IllustrationsRoute = IllustrationsRouteImport.update({
  id: '/illustrations',
  path: '/illustrations',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsApiRoute = DocsApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => DocsRoute,
} as any)
const DocsConceptsRoute = DocsConceptsRouteImport.update({
  id: '/concepts',
  path: '/concepts',
  getParentRoute: () => DocsRoute,
} as any)
const DocsExamplesRoute = DocsExamplesRouteImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => DocsRoute,
} as any)
const DocsHostingAndStorageRoute = DocsHostingAndStorageRouteImport.update({
  id: '/hosting-and-storage',
  path: '/hosting-and-storage',
  getParentRoute: () => DocsRoute,
} as any)
const DocsMathRoute = DocsMathRouteImport.update({
  id: '/math',
  path: '/math',
  getParentRoute: () => DocsRoute,
} as any)
const DocsModulesRoute = DocsModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => DocsRoute,
} as any)
const DocsPriorArtRoute = DocsPriorArtRouteImport.update({
  id: '/prior-art',
  path: '/prior-art',
  getParentRoute: () => DocsRoute,
} as any)
const DocsProjectorsRoute = DocsProjectorsRouteImport.update({
  id: '/projectors',
  path: '/projectors',
  getParentRoute: () => DocsRoute,
} as any)
const DocsQuickstartRoute = DocsQuickstartRouteImport.update({
  id: '/quickstart',
  path: '/quickstart',
  getParentRoute: () => DocsRoute,
} as any)
const DocsConceptsIndexRoute = DocsConceptsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsConceptsRoute,
} as any)
const DocsConceptsEventsAndEffectsRoute =
  DocsConceptsEventsAndEffectsRouteImport.update({
    id: '/events-and-effects',
    path: '/events-and-effects',
    getParentRoute: () => DocsConceptsRoute,
  } as any)
const DocsConceptsRunsAndThreadsRoute =
  DocsConceptsRunsAndThreadsRouteImport.update({
    id: '/runs-and-threads',
    path: '/runs-and-threads',
    getParentRoute: () => DocsConceptsRoute,
  } as any)
const DocsConceptsTypeSafetyRoute = DocsConceptsTypeSafetyRouteImport.update({
  id: '/type-safety',
  path: '/type-safety',
  getParentRoute: () => DocsConceptsRoute,
} as any)
const DocsConceptsWaitsAndReplayRoute =
  DocsConceptsWaitsAndReplayRouteImport.update({
    id: '/waits-and-replay',
    path: '/waits-and-replay',
    getParentRoute: () => DocsConceptsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/illustrations': typeof IllustrationsRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/concepts': typeof DocsConceptsRouteWithChildren
  '/docs/examples': typeof DocsExamplesRoute
  '/docs/hosting-and-storage': typeof DocsHostingAndStorageRoute
  '/docs/math': typeof DocsMathRoute
  '/docs/modules': typeof DocsModulesRoute
  '/docs/prior-art': typeof DocsPriorArtRoute
  '/docs/projectors': typeof DocsProjectorsRoute
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/concepts/events-and-effects': typeof DocsConceptsEventsAndEffectsRoute
  '/docs/concepts/runs-and-threads': typeof DocsConceptsRunsAndThreadsRoute
  '/docs/concepts/type-safety': typeof DocsConceptsTypeSafetyRoute
  '/docs/concepts/waits-and-replay': typeof DocsConceptsWaitsAndReplayRoute
  '/docs/concepts/': typeof DocsConceptsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/illustrations': typeof IllustrationsRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/examples': typeof DocsExamplesRoute
  '/docs/hosting-and-storage': typeof DocsHostingAndStorageRoute
  '/docs/math': typeof DocsMathRoute
  '/docs/modules': typeof DocsModulesRoute
  '/docs/prior-art': typeof DocsPriorArtRoute
  '/docs/projectors': typeof DocsProjectorsRoute
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/docs': typeof DocsIndexRoute
  '/docs/concepts/events-and-effects': typeof DocsConceptsEventsAndEffectsRoute
  '/docs/concepts/runs-and-threads': typeof DocsConceptsRunsAndThreadsRoute
  '/docs/concepts/type-safety': typeof DocsConceptsTypeSafetyRoute
  '/docs/concepts/waits-and-replay': typeof DocsConceptsWaitsAndReplayRoute
  '/docs/concepts': typeof DocsConceptsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/illustrations': typeof IllustrationsRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/concepts': typeof DocsConceptsRouteWithChildren
  '/docs/examples': typeof DocsExamplesRoute
  '/docs/hosting-and-storage': typeof DocsHostingAndStorageRoute
  '/docs/math': typeof DocsMathRoute
  '/docs/modules': typeof DocsModulesRoute
  '/docs/prior-art': typeof DocsPriorArtRoute
  '/docs/projectors': typeof DocsProjectorsRoute
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/concepts/events-and-effects': typeof DocsConceptsEventsAndEffectsRoute
  '/docs/concepts/runs-and-threads': typeof DocsConceptsRunsAndThreadsRoute
  '/docs/concepts/type-safety': typeof DocsConceptsTypeSafetyRoute
  '/docs/concepts/waits-and-replay': typeof DocsConceptsWaitsAndReplayRoute
  '/docs/concepts/': typeof DocsConceptsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/illustrations'
    | '/docs/api'
    | '/docs/concepts'
    | '/docs/examples'
    | '/docs/hosting-and-storage'
    | '/docs/math'
    | '/docs/modules'
    | '/docs/prior-art'
    | '/docs/projectors'
    | '/docs/quickstart'
    | '/docs/'
    | '/docs/concepts/events-and-effects'
    | '/docs/concepts/runs-and-threads'
    | '/docs/concepts/type-safety'
    | '/docs/concepts/waits-and-replay'
    | '/docs/concepts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/illustrations'
    | '/docs/api'
    | '/docs/examples'
    | '/docs/hosting-and-storage'
    | '/docs/math'
    | '/docs/modules'
    | '/docs/prior-art'
    | '/docs/projectors'
    | '/docs/quickstart'
    | '/docs'
    | '/docs/concepts/events-and-effects'
    | '/docs/concepts/runs-and-threads'
    | '/docs/concepts/type-safety'
    | '/docs/concepts/waits-and-replay'
    | '/docs/concepts'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/illustrations'
    | '/docs/api'
    | '/docs/concepts'
    | '/docs/examples'
    | '/docs/hosting-and-storage'
    | '/docs/math'
    | '/docs/modules'
    | '/docs/prior-art'
    | '/docs/projectors'
    | '/docs/quickstart'
    | '/docs/'
    | '/docs/concepts/events-and-effects'
    | '/docs/concepts/runs-and-threads'
    | '/docs/concepts/type-safety'
    | '/docs/concepts/waits-and-replay'
    | '/docs/concepts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRouteWithChildren
  IllustrationsRoute: typeof IllustrationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/illustrations': {
      id: '/illustrations'
      path: '/illustrations'
      fullPath: '/illustrations'
      preLoaderRoute: typeof IllustrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/api': {
      id: '/docs/api'
      path: '/api'
      fullPath: '/docs/api'
      preLoaderRoute: typeof DocsApiRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/concepts': {
      id: '/docs/concepts'
      path: '/concepts'
      fullPath: '/docs/concepts'
      preLoaderRoute: typeof DocsConceptsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/examples': {
      id: '/docs/examples'
      path: '/examples'
      fullPath: '/docs/examples'
      preLoaderRoute: typeof DocsExamplesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/hosting-and-storage': {
      id: '/docs/hosting-and-storage'
      path: '/hosting-and-storage'
      fullPath: '/docs/hosting-and-storage'
      preLoaderRoute: typeof DocsHostingAndStorageRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/math': {
      id: '/docs/math'
      path: '/math'
      fullPath: '/docs/math'
      preLoaderRoute: typeof DocsMathRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/modules': {
      id: '/docs/modules'
      path: '/modules'
      fullPath: '/docs/modules'
      preLoaderRoute: typeof DocsModulesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/prior-art': {
      id: '/docs/prior-art'
      path: '/prior-art'
      fullPath: '/docs/prior-art'
      preLoaderRoute: typeof DocsPriorArtRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/projectors': {
      id: '/docs/projectors'
      path: '/projectors'
      fullPath: '/docs/projectors'
      preLoaderRoute: typeof DocsProjectorsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/quickstart': {
      id: '/docs/quickstart'
      path: '/quickstart'
      fullPath: '/docs/quickstart'
      preLoaderRoute: typeof DocsQuickstartRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/concepts/': {
      id: '/docs/concepts/'
      path: '/'
      fullPath: '/docs/concepts/'
      preLoaderRoute: typeof DocsConceptsIndexRouteImport
      parentRoute: typeof DocsConceptsRoute
    }
    '/docs/concepts/events-and-effects': {
      id: '/docs/concepts/events-and-effects'
      path: '/events-and-effects'
      fullPath: '/docs/concepts/events-and-effects'
      preLoaderRoute: typeof DocsConceptsEventsAndEffectsRouteImport
      parentRoute: typeof DocsConceptsRoute
    }
    '/docs/concepts/runs-and-threads': {
      id: '/docs/concepts/runs-and-threads'
      path: '/runs-and-threads'
      fullPath: '/docs/concepts/runs-and-threads'
      preLoaderRoute: typeof DocsConceptsRunsAndThreadsRouteImport
      parentRoute: typeof DocsConceptsRoute
    }
    '/docs/concepts/type-safety': {
      id: '/docs/concepts/type-safety'
      path: '/type-safety'
      fullPath: '/docs/concepts/type-safety'
      preLoaderRoute: typeof DocsConceptsTypeSafetyRouteImport
      parentRoute: typeof DocsConceptsRoute
    }
    '/docs/concepts/waits-and-replay': {
      id: '/docs/concepts/waits-and-replay'
      path: '/waits-and-replay'
      fullPath: '/docs/concepts/waits-and-replay'
      preLoaderRoute: typeof DocsConceptsWaitsAndReplayRouteImport
      parentRoute: typeof DocsConceptsRoute
    }
  }
}

interface DocsConceptsRouteChildren {
  DocsConceptsEventsAndEffectsRoute: typeof DocsConceptsEventsAndEffectsRoute
  DocsConceptsRunsAndThreadsRoute: typeof DocsConceptsRunsAndThreadsRoute
  DocsConceptsTypeSafetyRoute: typeof DocsConceptsTypeSafetyRoute
  DocsConceptsWaitsAndReplayRoute: typeof DocsConceptsWaitsAndReplayRoute
  DocsConceptsIndexRoute: typeof DocsConceptsIndexRoute
}

const DocsConceptsRouteChildren: DocsConceptsRouteChildren = {
  DocsConceptsEventsAndEffectsRoute: DocsConceptsEventsAndEffectsRoute,
  DocsConceptsRunsAndThreadsRoute: DocsConceptsRunsAndThreadsRoute,
  DocsConceptsTypeSafetyRoute: DocsConceptsTypeSafetyRoute,
  DocsConceptsWaitsAndReplayRoute: DocsConceptsWaitsAndReplayRoute,
  DocsConceptsIndexRoute: DocsConceptsIndexRoute,
}

const DocsConceptsRouteWithChildren = DocsConceptsRoute._addFileChildren(
  DocsConceptsRouteChildren,
)

interface DocsRouteChildren {
  DocsApiRoute: typeof DocsApiRoute
  DocsConceptsRoute: typeof DocsConceptsRouteWithChildren
  DocsExamplesRoute: typeof DocsExamplesRoute
  DocsHostingAndStorageRoute: typeof DocsHostingAndStorageRoute
  DocsMathRoute: typeof DocsMathRoute
  DocsModulesRoute: typeof DocsModulesRoute
  DocsPriorArtRoute: typeof DocsPriorArtRoute
  DocsProjectorsRoute: typeof DocsProjectorsRoute
  DocsQuickstartRoute: typeof DocsQuickstartRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsApiRoute: DocsApiRoute,
  DocsConceptsRoute: DocsConceptsRouteWithChildren,
  DocsExamplesRoute: DocsExamplesRoute,
  DocsHostingAndStorageRoute: DocsHostingAndStorageRoute,
  DocsMathRoute: DocsMathRoute,
  DocsModulesRoute: DocsModulesRoute,
  DocsPriorArtRoute: DocsPriorArtRoute,
  DocsProjectorsRoute: DocsProjectorsRoute,
  DocsQuickstartRoute: DocsQuickstartRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRouteWithChildren,
  IllustrationsRoute: IllustrationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
