/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as IllustrationsRouteImport } from './routes/illustrations'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsAgentsRouteImport } from './routes/docs.agents'
import { Route as DocsApiRouteImport } from './routes/docs.api'
import { Route as DocsApprovalsRouteImport } from './routes/docs.approvals'
import { Route as DocsConceptsRouteImport } from './routes/docs.concepts'
import { Route as DocsEvaluatorRouteImport } from './routes/docs.evaluator'
import { Route as DocsExamplesRouteImport } from './routes/docs.examples'
import { Route as DocsHostingAndStorageRouteImport } from './routes/docs.hosting-and-storage'
import { Route as DocsIntegrationRouteImport } from './routes/docs.integration'
import { Route as DocsMathRouteImport } from './routes/docs.math'
import { Route as DocsModulesRouteImport } from './routes/docs.modules'
import { Route as DocsOperationsRouteImport } from './routes/docs.operations'
import { Route as DocsPriorArtRouteImport } from './routes/docs.prior-art'
import { Route as DocsProjectorsRouteImport } from './routes/docs.projectors'
import { Route as DocsQuickstartRouteImport } from './routes/docs.quickstart'
import { Route as DocsReliabilityRouteImport } from './routes/docs.reliability'
import { Route as DocsSecurityRouteImport } from './routes/docs.security'
import { Route as DocsTestingRouteImport } from './routes/docs.testing'
import { Route as DocsTroubleshootingRouteImport } from './routes/docs.troubleshooting'
import { Route as DocsVersioningRouteImport } from './routes/docs.versioning'
import { Route as DocsWhenToUseRouteImport } from './routes/docs.when-to-use'
import { Route as DocsConceptsIndexRouteImport } from './routes/docs.concepts.index'
import { Route as DocsConceptsEventsAndEffectsRouteImport } from './routes/docs.concepts.events-and-effects'
import { Route as DocsConceptsRunsAndThreadsRouteImport } from './routes/docs.concepts.runs-and-threads'
import { Route as DocsConceptsTypeSafetyRouteImport } from './routes/docs.concepts.type-safety'
import { Route as DocsConceptsWaitsAndReplayRouteImport } from './routes/docs.concepts.waits-and-replay'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IllustrationsRoute = IllustrationsRouteImport.update({
  id: '/illustrations',
  path: '/illustrations',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsAgentsRoute = DocsAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => DocsRoute,
} as any)
const DocsApiRoute = DocsApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => DocsRoute,
} as any)
const DocsApprovalsRoute = DocsApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => DocsRoute,
} as any)
const DocsConceptsRoute = DocsConceptsRouteImport.update({
  id: '/concepts',
  path: '/concepts',
  getParentRoute: () => DocsRoute,
} as any)
const DocsEvaluatorRoute = DocsEvaluatorRouteImport.update({
  id: '/evaluator',
  path: '/evaluator',
  getParentRoute: () => DocsRoute,
} as any)
const DocsExamplesRoute = DocsExamplesRouteImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => DocsRoute,
} as any)
const DocsHostingAndStorageRoute = DocsHostingAndStorageRouteImport.update({
  id: '/hosting-and-storage',
  path: '/hosting-and-storage',
  getParentRoute: () => DocsRoute,
} as any)
const DocsIntegrationRoute = DocsIntegrationRouteImport.update({
  id: '/integration',
  path: '/integration',
  getParentRoute: () => DocsRoute,
} as any)
const DocsMathRoute = DocsMathRouteImport.update({
  id: '/math',
  path: '/math',
  getParentRoute: () => DocsRoute,
} as any)
const DocsModulesRoute = DocsModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => DocsRoute,
} as any)
const DocsOperationsRoute = DocsOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => DocsRoute,
} as any)
const DocsPriorArtRoute = DocsPriorArtRouteImport.update({
  id: '/prior-art',
  path: '/prior-art',
  getParentRoute: () => DocsRoute,
} as any)
const DocsProjectorsRoute = DocsProjectorsRouteImport.update({
  id: '/projectors',
  path: '/projectors',
  getParentRoute: () => DocsRoute,
} as any)
const DocsQuickstartRoute = DocsQuickstartRouteImport.update({
  id: '/quickstart',
  path: '/quickstart',
  getParentRoute: () => DocsRoute,
} as any)
const DocsReliabilityRoute = DocsReliabilityRouteImport.update({
  id: '/reliability',
  path: '/reliability',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSecurityRoute = DocsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => DocsRoute,
} as any)
const DocsTestingRoute = DocsTestingRouteImport.update({
  id: '/testing',
  path: '/testing',
  getParentRoute: () => DocsRoute,
} as any)
const DocsTroubleshootingRoute = DocsTroubleshootingRouteImport.update({
  id: '/troubleshooting',
  path: '/troubleshooting',
  getParentRoute: () => DocsRoute,
} as any)
const DocsVersioningRoute = DocsVersioningRouteImport.update({
  id: '/versioning',
  path: '/versioning',
  getParentRoute: () => DocsRoute,
} as any)
const DocsWhenToUseRoute = DocsWhenToUseRouteImport.update({
  id: '/when-to-use',
  path: '/when-to-use',
  getParentRoute: () => DocsRoute,
} as any)
const DocsConceptsIndexRoute = DocsConceptsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsConceptsRoute,
} as any)
const DocsConceptsEventsAndEffectsRoute =
  DocsConceptsEventsAndEffectsRouteImport.update({
    id: '/events-and-effects',
    path: '/events-and-effects',
    getParentRoute: () => DocsConceptsRoute,
  } as any)
const DocsConceptsRunsAndThreadsRoute =
  DocsConceptsRunsAndThreadsRouteImport.update({
    id: '/runs-and-threads',
    path: '/runs-and-threads',
    getParentRoute: () => DocsConceptsRoute,
  } as any)
const DocsConceptsTypeSafetyRoute = DocsConceptsTypeSafetyRouteImport.update({
  id: '/type-safety',
  path: '/type-safety',
  getParentRoute: () => DocsConceptsRoute,
} as any)
const DocsConceptsWaitsAndReplayRoute =
  DocsConceptsWaitsAndReplayRouteImport.update({
    id: '/waits-and-replay',
    path: '/waits-and-replay',
    getParentRoute: () => DocsConceptsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/illustrations': typeof IllustrationsRoute
  '/docs/agents': typeof DocsAgentsRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/approvals': typeof DocsApprovalsRoute
  '/docs/concepts': typeof DocsConceptsRouteWithChildren
  '/docs/evaluator': typeof DocsEvaluatorRoute
  '/docs/examples': typeof DocsExamplesRoute
  '/docs/hosting-and-storage': typeof DocsHostingAndStorageRoute
  '/docs/integration': typeof DocsIntegrationRoute
  '/docs/math': typeof DocsMathRoute
  '/docs/modules': typeof DocsModulesRoute
  '/docs/operations': typeof DocsOperationsRoute
  '/docs/prior-art': typeof DocsPriorArtRoute
  '/docs/projectors': typeof DocsProjectorsRoute
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/docs/reliability': typeof DocsReliabilityRoute
  '/docs/security': typeof DocsSecurityRoute
  '/docs/testing': typeof DocsTestingRoute
  '/docs/troubleshooting': typeof DocsTroubleshootingRoute
  '/docs/versioning': typeof DocsVersioningRoute
  '/docs/when-to-use': typeof DocsWhenToUseRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/concepts/events-and-effects': typeof DocsConceptsEventsAndEffectsRoute
  '/docs/concepts/runs-and-threads': typeof DocsConceptsRunsAndThreadsRoute
  '/docs/concepts/type-safety': typeof DocsConceptsTypeSafetyRoute
  '/docs/concepts/waits-and-replay': typeof DocsConceptsWaitsAndReplayRoute
  '/docs/concepts/': typeof DocsConceptsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/illustrations': typeof IllustrationsRoute
  '/docs/agents': typeof DocsAgentsRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/approvals': typeof DocsApprovalsRoute
  '/docs/evaluator': typeof DocsEvaluatorRoute
  '/docs/examples': typeof DocsExamplesRoute
  '/docs/hosting-and-storage': typeof DocsHostingAndStorageRoute
  '/docs/integration': typeof DocsIntegrationRoute
  '/docs/math': typeof DocsMathRoute
  '/docs/modules': typeof DocsModulesRoute
  '/docs/operations': typeof DocsOperationsRoute
  '/docs/prior-art': typeof DocsPriorArtRoute
  '/docs/projectors': typeof DocsProjectorsRoute
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/docs/reliability': typeof DocsReliabilityRoute
  '/docs/security': typeof DocsSecurityRoute
  '/docs/testing': typeof DocsTestingRoute
  '/docs/troubleshooting': typeof DocsTroubleshootingRoute
  '/docs/versioning': typeof DocsVersioningRoute
  '/docs/when-to-use': typeof DocsWhenToUseRoute
  '/docs': typeof DocsIndexRoute
  '/docs/concepts/events-and-effects': typeof DocsConceptsEventsAndEffectsRoute
  '/docs/concepts/runs-and-threads': typeof DocsConceptsRunsAndThreadsRoute
  '/docs/concepts/type-safety': typeof DocsConceptsTypeSafetyRoute
  '/docs/concepts/waits-and-replay': typeof DocsConceptsWaitsAndReplayRoute
  '/docs/concepts': typeof DocsConceptsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/illustrations': typeof IllustrationsRoute
  '/docs/agents': typeof DocsAgentsRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/approvals': typeof DocsApprovalsRoute
  '/docs/concepts': typeof DocsConceptsRouteWithChildren
  '/docs/evaluator': typeof DocsEvaluatorRoute
  '/docs/examples': typeof DocsExamplesRoute
  '/docs/hosting-and-storage': typeof DocsHostingAndStorageRoute
  '/docs/integration': typeof DocsIntegrationRoute
  '/docs/math': typeof DocsMathRoute
  '/docs/modules': typeof DocsModulesRoute
  '/docs/operations': typeof DocsOperationsRoute
  '/docs/prior-art': typeof DocsPriorArtRoute
  '/docs/projectors': typeof DocsProjectorsRoute
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/docs/reliability': typeof DocsReliabilityRoute
  '/docs/security': typeof DocsSecurityRoute
  '/docs/testing': typeof DocsTestingRoute
  '/docs/troubleshooting': typeof DocsTroubleshootingRoute
  '/docs/versioning': typeof DocsVersioningRoute
  '/docs/when-to-use': typeof DocsWhenToUseRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/concepts/events-and-effects': typeof DocsConceptsEventsAndEffectsRoute
  '/docs/concepts/runs-and-threads': typeof DocsConceptsRunsAndThreadsRoute
  '/docs/concepts/type-safety': typeof DocsConceptsTypeSafetyRoute
  '/docs/concepts/waits-and-replay': typeof DocsConceptsWaitsAndReplayRoute
  '/docs/concepts/': typeof DocsConceptsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/illustrations'
    | '/docs/agents'
    | '/docs/api'
    | '/docs/approvals'
    | '/docs/concepts'
    | '/docs/evaluator'
    | '/docs/examples'
    | '/docs/hosting-and-storage'
    | '/docs/integration'
    | '/docs/math'
    | '/docs/modules'
    | '/docs/operations'
    | '/docs/prior-art'
    | '/docs/projectors'
    | '/docs/quickstart'
    | '/docs/reliability'
    | '/docs/security'
    | '/docs/testing'
    | '/docs/troubleshooting'
    | '/docs/versioning'
    | '/docs/when-to-use'
    | '/docs/'
    | '/docs/concepts/events-and-effects'
    | '/docs/concepts/runs-and-threads'
    | '/docs/concepts/type-safety'
    | '/docs/concepts/waits-and-replay'
    | '/docs/concepts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/illustrations'
    | '/docs/agents'
    | '/docs/api'
    | '/docs/approvals'
    | '/docs/evaluator'
    | '/docs/examples'
    | '/docs/hosting-and-storage'
    | '/docs/integration'
    | '/docs/math'
    | '/docs/modules'
    | '/docs/operations'
    | '/docs/prior-art'
    | '/docs/projectors'
    | '/docs/quickstart'
    | '/docs/reliability'
    | '/docs/security'
    | '/docs/testing'
    | '/docs/troubleshooting'
    | '/docs/versioning'
    | '/docs/when-to-use'
    | '/docs'
    | '/docs/concepts/events-and-effects'
    | '/docs/concepts/runs-and-threads'
    | '/docs/concepts/type-safety'
    | '/docs/concepts/waits-and-replay'
    | '/docs/concepts'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/illustrations'
    | '/docs/agents'
    | '/docs/api'
    | '/docs/approvals'
    | '/docs/concepts'
    | '/docs/evaluator'
    | '/docs/examples'
    | '/docs/hosting-and-storage'
    | '/docs/integration'
    | '/docs/math'
    | '/docs/modules'
    | '/docs/operations'
    | '/docs/prior-art'
    | '/docs/projectors'
    | '/docs/quickstart'
    | '/docs/reliability'
    | '/docs/security'
    | '/docs/testing'
    | '/docs/troubleshooting'
    | '/docs/versioning'
    | '/docs/when-to-use'
    | '/docs/'
    | '/docs/concepts/events-and-effects'
    | '/docs/concepts/runs-and-threads'
    | '/docs/concepts/type-safety'
    | '/docs/concepts/waits-and-replay'
    | '/docs/concepts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRouteWithChildren
  IllustrationsRoute: typeof IllustrationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/illustrations': {
      id: '/illustrations'
      path: '/illustrations'
      fullPath: '/illustrations'
      preLoaderRoute: typeof IllustrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/agents': {
      id: '/docs/agents'
      path: '/agents'
      fullPath: '/docs/agents'
      preLoaderRoute: typeof DocsAgentsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/api': {
      id: '/docs/api'
      path: '/api'
      fullPath: '/docs/api'
      preLoaderRoute: typeof DocsApiRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/approvals': {
      id: '/docs/approvals'
      path: '/approvals'
      fullPath: '/docs/approvals'
      preLoaderRoute: typeof DocsApprovalsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/concepts': {
      id: '/docs/concepts'
      path: '/concepts'
      fullPath: '/docs/concepts'
      preLoaderRoute: typeof DocsConceptsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/evaluator': {
      id: '/docs/evaluator'
      path: '/evaluator'
      fullPath: '/docs/evaluator'
      preLoaderRoute: typeof DocsEvaluatorRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/examples': {
      id: '/docs/examples'
      path: '/examples'
      fullPath: '/docs/examples'
      preLoaderRoute: typeof DocsExamplesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/hosting-and-storage': {
      id: '/docs/hosting-and-storage'
      path: '/hosting-and-storage'
      fullPath: '/docs/hosting-and-storage'
      preLoaderRoute: typeof DocsHostingAndStorageRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/integration': {
      id: '/docs/integration'
      path: '/integration'
      fullPath: '/docs/integration'
      preLoaderRoute: typeof DocsIntegrationRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/math': {
      id: '/docs/math'
      path: '/math'
      fullPath: '/docs/math'
      preLoaderRoute: typeof DocsMathRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/modules': {
      id: '/docs/modules'
      path: '/modules'
      fullPath: '/docs/modules'
      preLoaderRoute: typeof DocsModulesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/operations': {
      id: '/docs/operations'
      path: '/operations'
      fullPath: '/docs/operations'
      preLoaderRoute: typeof DocsOperationsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/prior-art': {
      id: '/docs/prior-art'
      path: '/prior-art'
      fullPath: '/docs/prior-art'
      preLoaderRoute: typeof DocsPriorArtRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/projectors': {
      id: '/docs/projectors'
      path: '/projectors'
      fullPath: '/docs/projectors'
      preLoaderRoute: typeof DocsProjectorsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/quickstart': {
      id: '/docs/quickstart'
      path: '/quickstart'
      fullPath: '/docs/quickstart'
      preLoaderRoute: typeof DocsQuickstartRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/reliability': {
      id: '/docs/reliability'
      path: '/reliability'
      fullPath: '/docs/reliability'
      preLoaderRoute: typeof DocsReliabilityRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/security': {
      id: '/docs/security'
      path: '/security'
      fullPath: '/docs/security'
      preLoaderRoute: typeof DocsSecurityRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/testing': {
      id: '/docs/testing'
      path: '/testing'
      fullPath: '/docs/testing'
      preLoaderRoute: typeof DocsTestingRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/troubleshooting': {
      id: '/docs/troubleshooting'
      path: '/troubleshooting'
      fullPath: '/docs/troubleshooting'
      preLoaderRoute: typeof DocsTroubleshootingRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/versioning': {
      id: '/docs/versioning'
      path: '/versioning'
      fullPath: '/docs/versioning'
      preLoaderRoute: typeof DocsVersioningRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/when-to-use': {
      id: '/docs/when-to-use'
      path: '/when-to-use'
      fullPath: '/docs/when-to-use'
      preLoaderRoute: typeof DocsWhenToUseRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/concepts/': {
      id: '/docs/concepts/'
      path: '/'
      fullPath: '/docs/concepts/'
      preLoaderRoute: typeof DocsConceptsIndexRouteImport
      parentRoute: typeof DocsConceptsRoute
    }
    '/docs/concepts/events-and-effects': {
      id: '/docs/concepts/events-and-effects'
      path: '/events-and-effects'
      fullPath: '/docs/concepts/events-and-effects'
      preLoaderRoute: typeof DocsConceptsEventsAndEffectsRouteImport
      parentRoute: typeof DocsConceptsRoute
    }
    '/docs/concepts/runs-and-threads': {
      id: '/docs/concepts/runs-and-threads'
      path: '/runs-and-threads'
      fullPath: '/docs/concepts/runs-and-threads'
      preLoaderRoute: typeof DocsConceptsRunsAndThreadsRouteImport
      parentRoute: typeof DocsConceptsRoute
    }
    '/docs/concepts/type-safety': {
      id: '/docs/concepts/type-safety'
      path: '/type-safety'
      fullPath: '/docs/concepts/type-safety'
      preLoaderRoute: typeof DocsConceptsTypeSafetyRouteImport
      parentRoute: typeof DocsConceptsRoute
    }
    '/docs/concepts/waits-and-replay': {
      id: '/docs/concepts/waits-and-replay'
      path: '/waits-and-replay'
      fullPath: '/docs/concepts/waits-and-replay'
      preLoaderRoute: typeof DocsConceptsWaitsAndReplayRouteImport
      parentRoute: typeof DocsConceptsRoute
    }
  }
}

interface DocsConceptsRouteChildren {
  DocsConceptsEventsAndEffectsRoute: typeof DocsConceptsEventsAndEffectsRoute
  DocsConceptsRunsAndThreadsRoute: typeof DocsConceptsRunsAndThreadsRoute
  DocsConceptsTypeSafetyRoute: typeof DocsConceptsTypeSafetyRoute
  DocsConceptsWaitsAndReplayRoute: typeof DocsConceptsWaitsAndReplayRoute
  DocsConceptsIndexRoute: typeof DocsConceptsIndexRoute
}

const DocsConceptsRouteChildren: DocsConceptsRouteChildren = {
  DocsConceptsEventsAndEffectsRoute: DocsConceptsEventsAndEffectsRoute,
  DocsConceptsRunsAndThreadsRoute: DocsConceptsRunsAndThreadsRoute,
  DocsConceptsTypeSafetyRoute: DocsConceptsTypeSafetyRoute,
  DocsConceptsWaitsAndReplayRoute: DocsConceptsWaitsAndReplayRoute,
  DocsConceptsIndexRoute: DocsConceptsIndexRoute,
}

const DocsConceptsRouteWithChildren = DocsConceptsRoute._addFileChildren(
  DocsConceptsRouteChildren,
)

interface DocsRouteChildren {
  DocsAgentsRoute: typeof DocsAgentsRoute
  DocsApiRoute: typeof DocsApiRoute
  DocsApprovalsRoute: typeof DocsApprovalsRoute
  DocsConceptsRoute: typeof DocsConceptsRouteWithChildren
  DocsEvaluatorRoute: typeof DocsEvaluatorRoute
  DocsExamplesRoute: typeof DocsExamplesRoute
  DocsHostingAndStorageRoute: typeof DocsHostingAndStorageRoute
  DocsIntegrationRoute: typeof DocsIntegrationRoute
  DocsMathRoute: typeof DocsMathRoute
  DocsModulesRoute: typeof DocsModulesRoute
  DocsOperationsRoute: typeof DocsOperationsRoute
  DocsPriorArtRoute: typeof DocsPriorArtRoute
  DocsProjectorsRoute: typeof DocsProjectorsRoute
  DocsQuickstartRoute: typeof DocsQuickstartRoute
  DocsReliabilityRoute: typeof DocsReliabilityRoute
  DocsSecurityRoute: typeof DocsSecurityRoute
  DocsTestingRoute: typeof DocsTestingRoute
  DocsTroubleshootingRoute: typeof DocsTroubleshootingRoute
  DocsVersioningRoute: typeof DocsVersioningRoute
  DocsWhenToUseRoute: typeof DocsWhenToUseRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsAgentsRoute: DocsAgentsRoute,
  DocsApiRoute: DocsApiRoute,
  DocsApprovalsRoute: DocsApprovalsRoute,
  DocsConceptsRoute: DocsConceptsRouteWithChildren,
  DocsEvaluatorRoute: DocsEvaluatorRoute,
  DocsExamplesRoute: DocsExamplesRoute,
  DocsHostingAndStorageRoute: DocsHostingAndStorageRoute,
  DocsIntegrationRoute: DocsIntegrationRoute,
  DocsMathRoute: DocsMathRoute,
  DocsModulesRoute: DocsModulesRoute,
  DocsOperationsRoute: DocsOperationsRoute,
  DocsPriorArtRoute: DocsPriorArtRoute,
  DocsProjectorsRoute: DocsProjectorsRoute,
  DocsQuickstartRoute: DocsQuickstartRoute,
  DocsReliabilityRoute: DocsReliabilityRoute,
  DocsSecurityRoute: DocsSecurityRoute,
  DocsTestingRoute: DocsTestingRoute,
  DocsTroubleshootingRoute: DocsTroubleshootingRoute,
  DocsVersioningRoute: DocsVersioningRoute,
  DocsWhenToUseRoute: DocsWhenToUseRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRouteWithChildren,
  IllustrationsRoute: IllustrationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
